import type {
  AllocationSlice,
  InvestAsset,
  InvestPlatform,
  PerformancePeriod,
  PerformancePoint,
  PortfolioStats,
} from "@/src/features/invest/types";

export const USD_TO_NGN = 1575;

export const INVEST_PLATFORMS: InvestPlatform[] = [
  {
    key: "bamboo",
    name: "Bamboo",
    subtitle: "US Stocks & ETFs",
    emoji: "🎋",
    gradientFrom: "rgba(52,199,89,0.20)",
    gradientTo: "rgba(52,199,89,0.04)",
    instructions: [
      "Log in to your Bamboo account",
      "Go to Settings → API Access",
      "Generate a read-only API key",
      "Paste the key below",
    ],
    apiLabel: "API Key",
    status: "linked",
  },
  {
    key: "risevest",
    name: "Risevest",
    subtitle: "Dollar investments",
    emoji: "📈",
    gradientFrom: "rgba(61,110,255,0.18)",
    gradientTo: "rgba(61,110,255,0.04)",
    instructions: [
      "Log in to your Risevest account",
      "Open Settings → Portfolio Access",
      "Create a read-only access token",
      "Paste the token below",
    ],
    apiLabel: "Access Token",
    status: "unlinked",
  },
  {
    key: "chaka",
    name: "Chaka",
    subtitle: "Nigerian & US stocks",
    emoji: "🔷",
    gradientFrom: "rgba(168,85,247,0.18)",
    gradientTo: "rgba(168,85,247,0.04)",
    instructions: [
      "Log in to your Chaka account",
      "Go to Developer Settings",
      "Generate a portfolio read key",
      "Paste the key below",
    ],
    apiLabel: "API Key",
    status: "unlinked",
  },
  {
    key: "binance",
    name: "Binance",
    subtitle: "Cryptocurrency",
    emoji: "₿",
    gradientFrom: "rgba(245,158,11,0.20)",
    gradientTo: "rgba(245,158,11,0.05)",
    instructions: [
      "Log in to your Binance account",
      "Go to Settings → API Management",
      "Generate a read-only API key",
      "Paste the key below",
    ],
    apiLabel: "API Key",
    status: "linked",
  },
  {
    key: "cowrywise",
    name: "Cowrywise",
    subtitle: "Savings & Investments",
    emoji: "🐚",
    gradientFrom: "rgba(34,211,238,0.16)",
    gradientTo: "rgba(34,211,238,0.04)",
    instructions: [
      "Log in to your Cowrywise account",
      "Open Settings → Integrations",
      "Generate a read-only access key",
      "Paste the key below",
    ],
    apiLabel: "Access Key",
    status: "linked",
  },
  {
    key: "piggyvest",
    name: "PiggyVest",
    subtitle: "Savings & Returns",
    emoji: "🐷",
    gradientFrom: "rgba(236,72,153,0.16)",
    gradientTo: "rgba(236,72,153,0.04)",
    instructions: [
      "Log in to your PiggyVest account",
      "Go to Settings → API Keys",
      "Generate a read-only API key",
      "Paste the key below",
    ],
    apiLabel: "API Key",
    status: "unlinked",
  },
];

export const INVEST_ASSETS: InvestAsset[] = [
  {
    id: "btc",
    symbol: "BTC",
    name: "Bitcoin",
    emoji: "₿",
    platform: "binance",
    category: "crypto",
    currentPriceUsd: 73125,
    currentPriceNgn: 73125 * USD_TO_NGN,
    changePercent: 12.5,
    quantity: 0.015,
    averagePriceUsd: 65000,
    totalValueUsd: 1937.5,
    totalValueNgn: 3003125,
    profitLossNgn: 3001613.75,
    activity: [
      {
        id: "btc-a1",
        type: "buy",
        label: "Bought 0.25 BTC",
        date: "3/28/2026",
        amountNgn: 25000,
      },
      {
        id: "btc-a2",
        type: "buy",
        label: "Bought 0.5 BTC",
        date: "3/23/2026",
        amountNgn: 50000,
      },
    ],
  },
  {
    id: "aapl",
    symbol: "AAPL",
    name: "Apple Inc.",
    emoji: "🍎",
    platform: "bamboo",
    category: "stocks",
    currentPriceUsd: 212,
    currentPriceNgn: 212 * USD_TO_NGN,
    changePercent: 3.87,
    quantity: 13.14,
    averagePriceUsd: 185,
    totalValueUsd: 2780.8,
    totalValueNgn: 4379757.5,
    profitLossNgn: 559650,
    activity: [
      {
        id: "aapl-a1",
        type: "buy",
        label: "Bought AAPL",
        date: "3/18/2026",
        amountNgn: 120000,
      },
    ],
  },
  {
    id: "googl",
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    emoji: "🔍",
    platform: "bamboo",
    category: "stocks",
    currentPriceUsd: 171.5,
    currentPriceNgn: 171.5 * USD_TO_NGN,
    changePercent: 3.26,
    quantity: 6.67,
    averagePriceUsd: 160,
    totalValueUsd: 1143.9,
    totalValueNgn: 1801154.25,
    profitLossNgn: 121900,
    activity: [
      {
        id: "googl-a1",
        type: "buy",
        label: "Bought GOOGL",
        date: "3/10/2026",
        amountNgn: 95000,
      },
    ],
  },
  {
    id: "tsla",
    symbol: "TSLA",
    name: "Tesla Inc.",
    emoji: "⚡",
    platform: "risevest",
    category: "stocks",
    currentPriceUsd: 299.5,
    currentPriceNgn: 299.5 * USD_TO_NGN,
    changePercent: -2.61,
    quantity: 10,
    averagePriceUsd: 307,
    totalValueUsd: 2995,
    totalValueNgn: 4717164.6,
    profitLossNgn: -118125,
    activity: [
      {
        id: "tsla-a1",
        type: "buy",
        label: "Bought TSLA",
        date: "2/28/2026",
        amountNgn: 180000,
      },
    ],
  },
  {
    id: "cwdf",
    symbol: "CWDF",
    name: "Dollar Fund",
    emoji: "💵",
    platform: "cowrywise",
    category: "funds",
    currentPriceUsd: 1,
    currentPriceNgn: USD_TO_NGN,
    changePercent: 8.2,
    quantity: 372.69,
    averagePriceUsd: 0.92,
    totalValueUsd: 372.69,
    totalValueNgn: 586985,
    profitLossNgn: 44000,
    activity: [
      {
        id: "cwdf-a1",
        type: "buy",
        label: "Funded Dollar Fund",
        date: "3/03/2026",
        amountNgn: 85000,
      },
    ],
  },
];

export const INVEST_PORTFOLIO_STATS: PortfolioStats = {
  totalValueNgn: 14488186350,
  totalValueUsd: 9195661.17,
  totalReturnsNgn: 13937204750,
  totalReturnsPercent: 2529.52,
  diversificationScore: 72,
};

export const ASSET_ALLOCATION: AllocationSlice[] = [
  { label: "Crypto", value: 3003125000, color: "#FF8A00" },
  { label: "Stocks", value: 10898076350, color: "#1F6EF2" },
  { label: "Funds", value: 586985000, color: "#50E3C2" },
];

export const PLATFORM_ALLOCATION: AllocationSlice[] = [
  { label: "Binance", value: 3003125000, color: "#20242E" },
  { label: "Bamboo", value: 6180911750, color: "#20242E" },
  { label: "Risevest", value: 4717164600, color: "#20242E" },
  { label: "Cowrywise", value: 586985000, color: "#20242E" },
];

export const PERFORMANCE_POINTS: Record<PerformancePeriod, PerformancePoint[]> = {
  "1W": [
    { x: "Mon", y: 42 },
    { x: "Tue", y: 48 },
    { x: "Wed", y: 46 },
    { x: "Thu", y: 53 },
    { x: "Fri", y: 51 },
    { x: "Sat", y: 57 },
    { x: "Sun", y: 60 },
  ],
  "1M": [
    { x: "1", y: 28 },
    { x: "5", y: 39 },
    { x: "9", y: 35 },
    { x: "13", y: 47 },
    { x: "17", y: 42 },
    { x: "21", y: 53 },
    { x: "25", y: 50 },
    { x: "28", y: 59 },
    { x: "30", y: 55 },
    { x: "31", y: 63 },
  ],
  "3M": [
    { x: "Jan", y: 24 },
    { x: "Feb", y: 38 },
    { x: "Mar", y: 61 },
  ],
  "1Y": [
    { x: "Q1", y: 18 },
    { x: "Q2", y: 31 },
    { x: "Q3", y: 49 },
    { x: "Q4", y: 66 },
  ],
  All: [
    { x: "2023", y: 10 },
    { x: "2024", y: 27 },
    { x: "2025", y: 49 },
    { x: "2026", y: 65 },
  ],
};