import { AppTheme } from "../types/theme";
import { semantic } from "./tokens";

export const lightTheme: AppTheme = {
  mode: "light",
  isDark: false,
  colors: {
    background: "#F6F7F9",
    backgroundSecondary: "#FFFFFF",
    surface: "#FFFFFF",
    surfaceElevated: "#FCFCFD",
    text: "#0A0D14",
    textSecondary: "#525866",
    textMuted: "#868C98",
    border: "#DFE3E8",
    borderSoft: "#EBEEF2",
    borderFocus: "#31E6B7",
    primary: "#22D3A6",
    primaryText: "#07120F",
    tint: "#22D3A6",
    tintSoft: "rgba(34,211,166,0.14)",
    glow: "rgba(49,230,183,0.12)",
    inputBackground: "#F3F4F6",
    placeholder: "#98A2B3",
    icon: "#6B7280",
    iconFocused: "#1FCF9F",
    grid: "rgba(17,24,39,0.03)",
    success: semantic.success,
    shadow: "rgba(16,24,40,0.08)",
  },
  fonts: {
    headingRegular: "SoraRegular",
    headingSemiBold: "SoraSemiBold",
    headingBold: "SoraBold",
    bodyRegular: "InterRegular",
    bodyMedium: "InterMedium",
    bodySemiBold: "InterSemiBold",
    bodyBold: "InterBold",
  },
};