import type {
  AccountTransaction,
  Institution,
  LinkedAccount,
} from "@/src/features/accounts/types";

export const MOCK_LINKED_ACCOUNTS: LinkedAccount[] = [
  {
    id: "minta-wallet",
    bankName: "MiNTA",
    icon: "heart",
    logoColor: "#57F2C8",
    accountType: "Savings",
    accountNumber: "8012345678",
    balance: 385000,
    availableBalance: 385000,
    weekSpending: 143200,
    kind: "wallet",
    accent: "rgba(87,242,200,0.18)",
    accentSoft: "rgba(87,242,200,0.08)",
    syncedAtLabel: "Yesterday",
    totalIn: 0,
    totalOut: 0,
    canUnlink: true,
  },
  {
    id: "gtbank",
    bankName: "GTBank",
    icon: "business-outline",
    logoColor: "#F59E0B",
    accountType: "Savings",
    accountNumber: "0123456789",
    balance: 450000,
    availableBalance: 450000,
    kind: "bank",
    accent: "rgba(245,158,11,0.22)",
    accentSoft: "rgba(245,158,11,0.08)",
    syncedAtLabel: "Just now",
    totalIn: 850000,
    totalOut: 25000,
    canUnlink: true,
  },
  {
    id: "uba",
    bankName: "UBA",
    icon: "library-outline",
    logoColor: "#EF4444",
    accountType: "Current",
    accountNumber: "2098765432",
    balance: 1250000,
    availableBalance: 1250000,
    kind: "bank",
    accent: "rgba(239,68,68,0.20)",
    accentSoft: "rgba(239,68,68,0.08)",
    syncedAtLabel: "2 mins ago",
    totalIn: 850000,
    totalOut: 3500,
    canUnlink: true,
  },
  {
    id: "access",
    bankName: "Access Bank",
    icon: "briefcase-outline",
    logoColor: "#1F7BFF",
    accountType: "Current",
    accountNumber: "0567891234",
    balance: 320500,
    availableBalance: 320500,
    kind: "bank",
    accent: "rgba(31,123,255,0.20)",
    accentSoft: "rgba(31,123,255,0.08)",
    syncedAtLabel: "5 mins ago",
    totalIn: 0,
    totalOut: 0,
    canUnlink: true,
  },
  {
    id: "kuda",
    bankName: "Kuda",
    icon: "heart",
    logoColor: "#A855F7",
    accountType: "Savings",
    accountNumber: "2012345678",
    balance: 142000,
    availableBalance: 142000,
    kind: "bank",
    accent: "rgba(168,85,247,0.20)",
    accentSoft: "rgba(168,85,247,0.08)",
    syncedAtLabel: "10 mins ago",
    totalIn: 0,
    totalOut: 28700,
    canUnlink: true,
  },
];

export const MOCK_INSTITUTIONS: Institution[] = [
  { id: "gtbank", name: "GTBank", color: "#F59E0B", icon: "square" },
  { id: "uba", name: "UBA", color: "#EF4444", icon: "square" },
  { id: "access", name: "Access Bank", color: "#22C55E", icon: "square" },
  { id: "zenith", name: "Zenith Bank", color: "#DC2626", icon: "ellipse" },
  { id: "firstbank", name: "First Bank", color: "#F59E0B", icon: "ellipse" },
  { id: "opay", name: "OPay", color: "#22C55E", icon: "ellipse" },
  { id: "kuda", name: "Kuda", color: "#A855F7", icon: "ellipse" },
  { id: "moniepoint", name: "MoniePoint", color: "#2563EB", icon: "ellipse" },
  { id: "palmpay", name: "PalmPay", color: "#FACC15", icon: "ellipse" },
];

export const MOCK_TRANSACTIONS: AccountTransaction[] = [
  {
    id: "txn-shoprite",
    accountId: "kuda",
    title: "Shoprite Supermarket",
    amount: -15500,
    category: "Food & Dining",
    type: "expense",
    status: "completed",
    reference: "TXN20260125SHOP456",
    accountLabel: "Kuda",
    accountIcon: "heart",
    accountIconColor: "#A855F7",
    occurredAt: "2026-03-29T10:25:00.000Z",
    relativeLabel: "Yesterday",
  },
  {
    id: "txn-salary",
    accountId: "uba",
    title: "Salary - Tech Corp Ltd",
    amount: 850000,
    category: "Income",
    type: "income",
    status: "completed",
    reference: "TXN20260125SAL123",
    accountLabel: "UBA",
    accountIcon: "library-outline",
    accountIconColor: "#EF4444",
    occurredAt: "2026-03-28T09:10:00.000Z",
    relativeLabel: "2 days ago",
  },
  {
    id: "txn-uber",
    accountId: "kuda",
    title: "Uber Trip",
    amount: -3500,
    category: "Transport",
    type: "expense",
    status: "completed",
    reference: "TXN20260125UBR456",
    accountLabel: "Kuda",
    accountIcon: "heart",
    accountIconColor: "#A855F7",
    occurredAt: "2026-03-28T12:44:00.000Z",
    relativeLabel: "2 days ago",
  },
  {
    id: "txn-netflix",
    accountId: "kuda",
    title: "Netflix Subscription",
    amount: -4500,
    category: "Entertainment",
    type: "expense",
    status: "completed",
    reference: "TXN20260125NFLX721",
    accountLabel: "Kuda",
    accountIcon: "heart",
    accountIconColor: "#A855F7",
    occurredAt: "2026-03-27T08:10:00.000Z",
    relativeLabel: "3 days ago",
  },
  {
    id: "txn-transfer-kelechi",
    accountId: "gtbank",
    title: "Transfer to Kelechi Obi",
    amount: -25000,
    category: "Transfer",
    type: "expense",
    status: "completed",
    reference: "TXN20260125TRF220",
    accountLabel: "GTBank",
    accountIcon: "business-outline",
    accountIconColor: "#F59E0B",
    occurredAt: "2026-03-27T16:55:00.000Z",
    relativeLabel: "3 days ago",
  },
  {
    id: "txn-chicken-republic",
    accountId: "kuda",
    title: "Chicken Republic",
    amount: -5200,
    category: "Food & Dining",
    type: "expense",
    status: "completed",
    reference: "TXN20260125CHK110",
    accountLabel: "Kuda",
    accountIcon: "heart",
    accountIconColor: "#A855F7",
    occurredAt: "2026-03-26T15:21:00.000Z",
    relativeLabel: "4 days ago",
  },
  {
    id: "txn-dstv",
    accountId: "minta-wallet",
    title: "DSTv Premium",
    amount: -24500,
    category: "Bills",
    type: "expense",
    status: "completed",
    reference: "TXN20260125DST901",
    accountLabel: "MiNTA",
    accountIcon: "heart",
    accountIconColor: "#57F2C8",
    occurredAt: "2026-03-25T13:20:00.000Z",
    relativeLabel: "5 days ago",
  },
  {
    id: "txn-refund",
    accountId: "access",
    title: "Wallet Refund",
    amount: 12000,
    category: "Refund",
    type: "income",
    status: "completed",
    reference: "TXN20260125RFD331",
    accountLabel: "Access Bank",
    accountIcon: "briefcase-outline",
    accountIconColor: "#1F7BFF",
    occurredAt: "2026-03-24T11:05:00.000Z",
    relativeLabel: "6 days ago",
  },
  {
    id: "txn-bills-ikeja",
    accountId: "uba",
    title: "IKEJA Electric",
    amount: -18000,
    category: "Bills",
    type: "expense",
    status: "completed",
    reference: "TXN20260125IKD141",
    accountLabel: "UBA",
    accountIcon: "library-outline",
    accountIconColor: "#EF4444",
    occurredAt: "2026-03-24T07:35:00.000Z",
    relativeLabel: "6 days ago",
  },
  {
    id: "txn-cinema",
    accountId: "minta-wallet",
    title: "Filmhouse Cinema",
    amount: -8700,
    category: "Entertainment",
    type: "expense",
    status: "completed",
    reference: "TXN20260125FIL552",
    accountLabel: "MiNTA",
    accountIcon: "heart",
    accountIconColor: "#57F2C8",
    occurredAt: "2026-03-23T17:40:00.000Z",
    relativeLabel: "1 week ago",
  },
  {
    id: "txn-shopping-zara",
    accountId: "access",
    title: "Zara Purchase",
    amount: -28000,
    category: "Shopping",
    type: "expense",
    status: "completed",
    reference: "TXN20260125ZAR801",
    accountLabel: "Access Bank",
    accountIcon: "briefcase-outline",
    accountIconColor: "#1F7BFF",
    occurredAt: "2026-03-22T14:15:00.000Z",
    relativeLabel: "1 week ago",
  },
  {
    id: "txn-transfer-self",
    accountId: "minta-wallet",
    title: "Transfer from GTBank",
    amount: 150000,
    category: "Transfer",
    type: "income",
    status: "completed",
    reference: "TXN20260125SELF017",
    accountLabel: "MiNTA",
    accountIcon: "heart",
    accountIconColor: "#57F2C8",
    occurredAt: "2026-03-21T10:05:00.000Z",
    relativeLabel: "1 week ago",
  },
];

export const MOCK_CATEGORY_FILTERS = [
  "Income",
  "Transfer",
  "Shopping",
  "Entertainment",
  "Bills",
  "Transport",
  "Food & Dining",
  "Refund",
  "Subscription",
  "Other",
] as const;

export const MOCK_DATE_RANGE_PRESETS = [
  "Today",
  "Last 7 days",
  "This month",
  "Last month",
  "Last 3 months",
] as const;

export const MOCK_AMOUNT_PRESETS = [
  "Under ₦5,000",
  "₦5,000 - ₦20,000",
  "₦20,000 - ₦100,000",
  "Over ₦100,000",
] as const;